### ISSUE TITLE
Build With LLVM 4.0 will has error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gtm-http-fetcher#5]
```
What steps will reproduce the problem?
1. download gdata-objectivec-client r726
2. build it 
3. get error on build result

What is the expected output? What do you see instead?

src/gdata-objectivec-client-read-only-svn/Source/HTTPFetcher/GTMHTTPUploadFetche
r.m:463:55: error: format specifies type 'unsigned long' but the argument has 
type 'NSUInteger' (aka 'unsigned int') [-Werror,-Wformat]
    rangeStr = [NSString stringWithFormat:@"bytes */%lu", dataLen];
                                                    ~~^   ~~~~~~~
                                                    %u
src/gdata-objectivec-client-read-only-svn/Source/HTTPFetcher/GTMHTTPUploadFetche
r.m:469:44: error: format specifies type 'unsigned long' but the argument has 
type 'NSUInteger' (aka 'unsigned int') [-Werror,-Wformat]
    NSAssert2(offset < dataLen, @"offset %lu exceeds data length %lu",
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/S
DKs/MacOSX10.8.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSExce
ption.h:135:71: note: expanded from macro 'NSAssert2'
#define NSAssert2(condition, desc, arg1, arg2) NSAssert((condition), (desc), 
(arg1), (arg2))
                                                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/S
DKs/MacOSX10.8.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSExce
ption.h:102:40: note: expanded from macro 'NSAssert'
                lineNumber:__LINE__ description:(desc), ##__VA_ARGS__]; \
                                                 ^        ~~~~~~~~~~~
src/gdata-objectivec-client-read-only-svn/Source/HTTPFetcher/GTMHTTPUploadFetche
r.m:469:68: error: format specifies type 'unsigned long' but the argument has 
type 'NSUInteger' (aka 'unsigned int') [-Werror,-Wformat]
    NSAssert2(offset < dataLen, @"offset %lu exceeds data length %lu",
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/S
DKs/MacOSX10.8.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSExce
ption.h:135:71: note: expanded from macro 'NSAssert2'
#define NSAssert2(condition, desc, arg1, arg2) NSAssert((condition), (desc), 
(arg1), (arg2))
                                                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/S
DKs/MacOSX10.8.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSExce
ption.h:102:40: note: expanded from macro 'NSAssert'
                lineNumber:__LINE__ description:(desc), ##__VA_ARGS__]; \
                                                 ^        ~~~~~~~~~~~
src/gdata-objectivec-client-read-only-svn/Source/HTTPFetcher/GTMHTTPUploadFetche
r.m:489:53: error: format specifies type 'unsigned long' but the argument has 
type 'NSUInteger' (aka 'unsigned int') [-Werror,-Wformat]
    rangeStr = [NSString stringWithFormat:@"bytes %lu-%lu/%lu",
                                                  ~~^
                                                  %u
src/gdata-objectivec-client-read-only-svn/Source/HTTPFetcher/GTMHTTPUploadFetche
r.m:489:57: error: format specifies type 'unsigned long' but the argument has 
type 'unsigned int' [-Werror,-Wformat]
    rangeStr = [NSString stringWithFormat:@"bytes %lu-%lu/%lu",
                                                      ~~^
                                                      %u
src/gdata-objectivec-client-read-only-svn/Source/HTTPFetcher/GTMHTTPUploadFetche
r.m:489:61: error: format specifies type 'unsigned long' but the argument has 
type 'NSUInteger' (aka 'unsigned int') [-Werror,-Wformat]
    rangeStr = [NSString stringWithFormat:@"bytes %lu-%lu/%lu",
                                                          ~~^
                                                          %u
src/gdata-objectivec-client-read-only-svn/Source/HTTPFetcher/GTMHTTPUploadFetche
r.m:491:48: error: format specifies type 'unsigned long' but the argument has 
type 'NSUInteger' (aka 'unsigned int') [-Werror,-Wformat]
    lengthStr = [NSString stringWithFormat:@"%lu", thisChunkSize];
                                             ~~^   ~~~~~~~~~~~~~
                                             %u
src/gdata-objectivec-client-read-only-svn/Source/HTTPFetcher/GTMHTTPUploadFetche
r.m:728:65: error: format specifies type 'unsigned long' but the argument has 
type 'NSUInteger' (aka 'unsigned int') [-Werror,-Wformat]
    NSString *rangeStr = [NSString stringWithFormat:@"bytes */%lu", dataLen];
                                                              ~~^   ~~~~~~~
                                                              %u
8 errors generated.

What version of the product are you using? On what operating system?

OS: Mac OSX 10.8
Xcode 4.4, LLVM 4.0

Please provide any additional information below.

I got this error on new llvm compiler, use gcc 4.2 will pass it.

It is some about string format error.
```

Original issue reported on code.google.com by `superbil` on 27 Jul 2012 at 5:16
